### ISSUE TITLE
Encode sound

### ISSUE THREAD

**Issue by septagram** [Milewski/video-loader#5]
Can it be used to reencode sound files (e.g., wav -> ogg)?

**Comment by milewski** [comment]
According to this [http://urby.ca/?p=153](http://urby.ca/?p=153) you can.... but it sounds very "hacky"

However i have another webpack-loader which can do exactly what you need [bin-exec-loader](https://github.com/milewski/bin-exec-loader)

you would go like this:

_(on a mac, but you can find your way around on any other platform)_

install [ffpmeg](http://stackoverflow.com/a/22209532/1564598)
```bash
brew install ffmpeg --with-libvorbis
```

and then according to this [ffmpeg-audio-format-conversions](https://linuxconfig.org/ffmpeg-audio-format-conversions)
```js
{
    test: /\.wav$/,
    use: [
        { loader: 'file-loader', options: {name: '[name].[ext]'} },
        {
            loader: 'bin-exec-loader',
            options: {
                binary: 'ffmpeg',
                prefix: '-',
                name: '[name].ogg',
                args: {
                    i: '[input]',
                    acodec: 'libvorbis',
                    $1: '[output]',
                    y: true
                }
            }
        }
    ]
}
```

```js
console.log(require('some-wav-file.wav'));

// ....public/path/some-wav-file.ogg
```

**Comment by septagram** [comment]
@milewski Thanks a lot for the help ^_^
